/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SamplesRouteImport } from './routes/samples'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisaCountryRouteImport } from './routes/visa.$country'
import { Route as UseCaseSlugRouteImport } from './routes/use-case.$slug'
import { Route as ServicesOnwardTicketRouteImport } from './routes/services.onward-ticket'
import { Route as ServicesHotelReservationRouteImport } from './routes/services.hotel-reservation'
import { Route as ServicesFlightReservationRouteImport } from './routes/services.flight-reservation'
import { Route as ServicesCoverLetterRouteImport } from './routes/services.cover-letter'
import { Route as OrderServiceRouteImport } from './routes/order.$service'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundsRouteImport } from './routes/legal.refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalDisclaimerRouteImport } from './routes/legal.disclaimer'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated.account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated.admin.testimonials'
import { Route as AuthenticatedAdminTemplatesRouteImport } from './routes/_authenticated.admin.templates'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated.admin.roles'
import { Route as AuthenticatedAdminPaymentLogsRouteImport } from './routes/_authenticated.admin.payment-logs'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated.admin.orders'
import { Route as AuthenticatedAdminGuidesRouteImport } from './routes/_authenticated.admin.guides'
import { Route as AuthenticatedAdminFaqsRouteImport } from './routes/_authenticated.admin.faqs'
import { Route as AuthenticatedAdminEmailLogsRouteImport } from './routes/_authenticated.admin.email-logs'
import { Route as AuthenticatedAdminCouponsRouteImport } from './routes/_authenticated.admin.coupons'
import { Route as AuthenticatedAdminCountriesRouteImport } from './routes/_authenticated.admin.countries'
import { Route as AuthenticatedAdminContactRouteImport } from './routes/_authenticated.admin.contact'
import { Route as AuthenticatedAdminBlogRouteImport } from './routes/_authenticated.admin.blog'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated.admin.activity'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAdminOrdersIdRouteImport } from './routes/_authenticated.admin.orders.$id'
import { Route as AuthenticatedAccountOrdersIdRouteImport } from './routes/_authenticated.account.orders.$id'

const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesRoute = SamplesRouteImport.update({
  id: '/samples',
  path: '/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaCountryRoute = VisaCountryRouteImport.update({
  id: '/visa/$country',
  path: '/visa/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCaseSlugRoute = UseCaseSlugRouteImport.update({
  id: '/use-case/$slug',
  path: '/use-case/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesOnwardTicketRoute = ServicesOnwardTicketRouteImport.update({
  id: '/services/onward-ticket',
  path: '/services/onward-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesHotelReservationRoute =
  ServicesHotelReservationRouteImport.update({
    id: '/services/hotel-reservation',
    path: '/services/hotel-reservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFlightReservationRoute =
  ServicesFlightReservationRouteImport.update({
    id: '/services/flight-reservation',
    path: '/services/flight-reservation',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCoverLetterRoute = ServicesCoverLetterRouteImport.update({
  id: '/services/cover-letter',
  path: '/services/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderServiceRoute = OrderServiceRouteImport.update({
  id: '/order/$service',
  path: '/order/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDisclaimerRoute = LegalDisclaimerRouteImport.update({
  id: '/legal/disclaimer',
  path: '/legal/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTemplatesRoute =
  AuthenticatedAdminTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentLogsRoute =
  AuthenticatedAdminPaymentLogsRouteImport.update({
    id: '/payment-logs',
    path: '/payment-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGuidesRoute =
  AuthenticatedAdminGuidesRouteImport.update({
    id: '/guides',
    path: '/guides',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFaqsRoute = AuthenticatedAdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminEmailLogsRoute =
  AuthenticatedAdminEmailLogsRouteImport.update({
    id: '/email-logs',
    path: '/email-logs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCouponsRoute =
  AuthenticatedAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCountriesRoute =
  AuthenticatedAdminCountriesRouteImport.update({
    id: '/countries',
    path: '/countries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContactRoute =
  AuthenticatedAdminContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBlogRoute = AuthenticatedAdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminOrdersIdRoute =
  AuthenticatedAdminOrdersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminOrdersRoute,
  } as any)
const AuthenticatedAccountOrdersIdRoute =
  AuthenticatedAccountOrdersIdRouteImport.update({
    id: '/orders/$id',
    path: '/orders/$id',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/samples': typeof SamplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$service': typeof OrderServiceRoute
  '/services/cover-letter': typeof ServicesCoverLetterRoute
  '/services/flight-reservation': typeof ServicesFlightReservationRoute
  '/services/hotel-reservation': typeof ServicesHotelReservationRoute
  '/services/onward-ticket': typeof ServicesOnwardTicketRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
  '/visa/$country': typeof VisaCountryRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/email-logs': typeof AuthenticatedAdminEmailLogsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/payment-logs': typeof AuthenticatedAdminPaymentLogsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/samples': typeof SamplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$service': typeof OrderServiceRoute
  '/services/cover-letter': typeof ServicesCoverLetterRoute
  '/services/flight-reservation': typeof ServicesFlightReservationRoute
  '/services/hotel-reservation': typeof ServicesHotelReservationRoute
  '/services/onward-ticket': typeof ServicesOnwardTicketRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
  '/visa/$country': typeof VisaCountryRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/admin/contact': typeof AuthenticatedAdminContactRoute
  '/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/admin/email-logs': typeof AuthenticatedAdminEmailLogsRoute
  '/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/admin/payment-logs': typeof AuthenticatedAdminPaymentLogsRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/samples': typeof SamplesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track-order': typeof TrackOrderRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/disclaimer': typeof LegalDisclaimerRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/order/$service': typeof OrderServiceRoute
  '/services/cover-letter': typeof ServicesCoverLetterRoute
  '/services/flight-reservation': typeof ServicesFlightReservationRoute
  '/services/hotel-reservation': typeof ServicesHotelReservationRoute
  '/services/onward-ticket': typeof ServicesOnwardTicketRoute
  '/use-case/$slug': typeof UseCaseSlugRoute
  '/visa/$country': typeof VisaCountryRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/blog': typeof AuthenticatedAdminBlogRoute
  '/_authenticated/admin/contact': typeof AuthenticatedAdminContactRoute
  '/_authenticated/admin/countries': typeof AuthenticatedAdminCountriesRoute
  '/_authenticated/admin/coupons': typeof AuthenticatedAdminCouponsRoute
  '/_authenticated/admin/email-logs': typeof AuthenticatedAdminEmailLogsRoute
  '/_authenticated/admin/faqs': typeof AuthenticatedAdminFaqsRoute
  '/_authenticated/admin/guides': typeof AuthenticatedAdminGuidesRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRouteWithChildren
  '/_authenticated/admin/payment-logs': typeof AuthenticatedAdminPaymentLogsRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/templates': typeof AuthenticatedAdminTemplatesRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/account/orders/$id': typeof AuthenticatedAccountOrdersIdRoute
  '/_authenticated/admin/orders/$id': typeof AuthenticatedAdminOrdersIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/how-it-works'
    | '/pricing'
    | '/reviews'
    | '/samples'
    | '/sitemap.xml'
    | '/track-order'
    | '/account'
    | '/admin'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/success'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$service'
    | '/services/cover-letter'
    | '/services/flight-reservation'
    | '/services/hotel-reservation'
    | '/services/onward-ticket'
    | '/use-case/$slug'
    | '/visa/$country'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/contact'
    | '/admin/countries'
    | '/admin/coupons'
    | '/admin/email-logs'
    | '/admin/faqs'
    | '/admin/guides'
    | '/admin/orders'
    | '/admin/payment-logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin/'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/how-it-works'
    | '/pricing'
    | '/reviews'
    | '/samples'
    | '/sitemap.xml'
    | '/track-order'
    | '/account'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/success'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$service'
    | '/services/cover-letter'
    | '/services/flight-reservation'
    | '/services/hotel-reservation'
    | '/services/onward-ticket'
    | '/use-case/$slug'
    | '/visa/$country'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/contact'
    | '/admin/countries'
    | '/admin/coupons'
    | '/admin/email-logs'
    | '/admin/faqs'
    | '/admin/guides'
    | '/admin/orders'
    | '/admin/payment-logs'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/templates'
    | '/admin/testimonials'
    | '/admin'
    | '/account/orders/$id'
    | '/admin/orders/$id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/blog'
    | '/contact'
    | '/faq'
    | '/guides'
    | '/how-it-works'
    | '/pricing'
    | '/reviews'
    | '/samples'
    | '/sitemap.xml'
    | '/track-order'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/success'
    | '/guides/$slug'
    | '/legal/cookies'
    | '/legal/disclaimer'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/order/$service'
    | '/services/cover-letter'
    | '/services/flight-reservation'
    | '/services/hotel-reservation'
    | '/services/onward-ticket'
    | '/use-case/$slug'
    | '/visa/$country'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/blog'
    | '/_authenticated/admin/contact'
    | '/_authenticated/admin/countries'
    | '/_authenticated/admin/coupons'
    | '/_authenticated/admin/email-logs'
    | '/_authenticated/admin/faqs'
    | '/_authenticated/admin/guides'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/payment-logs'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/templates'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/'
    | '/_authenticated/account/orders/$id'
    | '/_authenticated/admin/orders/$id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  ReviewsRoute: typeof ReviewsRoute
  SamplesRoute: typeof SamplesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackOrderRoute: typeof TrackOrderRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalDisclaimerRoute: typeof LegalDisclaimerRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OrderServiceRoute: typeof OrderServiceRoute
  ServicesCoverLetterRoute: typeof ServicesCoverLetterRoute
  ServicesFlightReservationRoute: typeof ServicesFlightReservationRoute
  ServicesHotelReservationRoute: typeof ServicesHotelReservationRoute
  ServicesOnwardTicketRoute: typeof ServicesOnwardTicketRoute
  UseCaseSlugRoute: typeof UseCaseSlugRoute
  VisaCountryRoute: typeof VisaCountryRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples': {
      id: '/samples'
      path: '/samples'
      fullPath: '/samples'
      preLoaderRoute: typeof SamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa/$country': {
      id: '/visa/$country'
      path: '/visa/$country'
      fullPath: '/visa/$country'
      preLoaderRoute: typeof VisaCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-case/$slug': {
      id: '/use-case/$slug'
      path: '/use-case/$slug'
      fullPath: '/use-case/$slug'
      preLoaderRoute: typeof UseCaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/onward-ticket': {
      id: '/services/onward-ticket'
      path: '/services/onward-ticket'
      fullPath: '/services/onward-ticket'
      preLoaderRoute: typeof ServicesOnwardTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/hotel-reservation': {
      id: '/services/hotel-reservation'
      path: '/services/hotel-reservation'
      fullPath: '/services/hotel-reservation'
      preLoaderRoute: typeof ServicesHotelReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/flight-reservation': {
      id: '/services/flight-reservation'
      path: '/services/flight-reservation'
      fullPath: '/services/flight-reservation'
      preLoaderRoute: typeof ServicesFlightReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cover-letter': {
      id: '/services/cover-letter'
      path: '/services/cover-letter'
      fullPath: '/services/cover-letter'
      preLoaderRoute: typeof ServicesCoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$service': {
      id: '/order/$service'
      path: '/order/$service'
      fullPath: '/order/$service'
      preLoaderRoute: typeof OrderServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/disclaimer': {
      id: '/legal/disclaimer'
      path: '/legal/disclaimer'
      fullPath: '/legal/disclaimer'
      preLoaderRoute: typeof LegalDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/templates': {
      id: '/_authenticated/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AuthenticatedAdminTemplatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payment-logs': {
      id: '/_authenticated/admin/payment-logs'
      path: '/payment-logs'
      fullPath: '/admin/payment-logs'
      preLoaderRoute: typeof AuthenticatedAdminPaymentLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/guides': {
      id: '/_authenticated/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AuthenticatedAdminGuidesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/faqs': {
      id: '/_authenticated/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AuthenticatedAdminFaqsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/email-logs': {
      id: '/_authenticated/admin/email-logs'
      path: '/email-logs'
      fullPath: '/admin/email-logs'
      preLoaderRoute: typeof AuthenticatedAdminEmailLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/coupons': {
      id: '/_authenticated/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AuthenticatedAdminCouponsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/countries': {
      id: '/_authenticated/admin/countries'
      path: '/countries'
      fullPath: '/admin/countries'
      preLoaderRoute: typeof AuthenticatedAdminCountriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contact': {
      id: '/_authenticated/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AuthenticatedAdminContactRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blog': {
      id: '/_authenticated/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AuthenticatedAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/orders/$id': {
      id: '/_authenticated/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AuthenticatedAdminOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAdminOrdersRoute
    }
    '/_authenticated/account/orders/$id': {
      id: '/_authenticated/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AuthenticatedAccountOrdersIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountOrdersIdRoute: typeof AuthenticatedAccountOrdersIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountOrdersIdRoute: AuthenticatedAccountOrdersIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminOrdersRouteChildren {
  AuthenticatedAdminOrdersIdRoute: typeof AuthenticatedAdminOrdersIdRoute
}

const AuthenticatedAdminOrdersRouteChildren: AuthenticatedAdminOrdersRouteChildren =
  {
    AuthenticatedAdminOrdersIdRoute: AuthenticatedAdminOrdersIdRoute,
  }

const AuthenticatedAdminOrdersRouteWithChildren =
  AuthenticatedAdminOrdersRoute._addFileChildren(
    AuthenticatedAdminOrdersRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminBlogRoute: typeof AuthenticatedAdminBlogRoute
  AuthenticatedAdminContactRoute: typeof AuthenticatedAdminContactRoute
  AuthenticatedAdminCountriesRoute: typeof AuthenticatedAdminCountriesRoute
  AuthenticatedAdminCouponsRoute: typeof AuthenticatedAdminCouponsRoute
  AuthenticatedAdminEmailLogsRoute: typeof AuthenticatedAdminEmailLogsRoute
  AuthenticatedAdminFaqsRoute: typeof AuthenticatedAdminFaqsRoute
  AuthenticatedAdminGuidesRoute: typeof AuthenticatedAdminGuidesRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRouteWithChildren
  AuthenticatedAdminPaymentLogsRoute: typeof AuthenticatedAdminPaymentLogsRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTemplatesRoute: typeof AuthenticatedAdminTemplatesRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminBlogRoute: AuthenticatedAdminBlogRoute,
  AuthenticatedAdminContactRoute: AuthenticatedAdminContactRoute,
  AuthenticatedAdminCountriesRoute: AuthenticatedAdminCountriesRoute,
  AuthenticatedAdminCouponsRoute: AuthenticatedAdminCouponsRoute,
  AuthenticatedAdminEmailLogsRoute: AuthenticatedAdminEmailLogsRoute,
  AuthenticatedAdminFaqsRoute: AuthenticatedAdminFaqsRoute,
  AuthenticatedAdminGuidesRoute: AuthenticatedAdminGuidesRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRouteWithChildren,
  AuthenticatedAdminPaymentLogsRoute: AuthenticatedAdminPaymentLogsRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTemplatesRoute: AuthenticatedAdminTemplatesRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  GuidesRoute: GuidesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  ReviewsRoute: ReviewsRoute,
  SamplesRoute: SamplesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackOrderRoute: TrackOrderRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalDisclaimerRoute: LegalDisclaimerRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  OrderServiceRoute: OrderServiceRoute,
  ServicesCoverLetterRoute: ServicesCoverLetterRoute,
  ServicesFlightReservationRoute: ServicesFlightReservationRoute,
  ServicesHotelReservationRoute: ServicesHotelReservationRoute,
  ServicesOnwardTicketRoute: ServicesOnwardTicketRoute,
  UseCaseSlugRoute: UseCaseSlugRoute,
  VisaCountryRoute: VisaCountryRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
